# Generated by Django 4.2.4 on 2023-08-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_date",
            field=models.DateField(auto_now=True),
        ),
    ]
